# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello，全仔！
brief-intro: 嵌入式图像处理与机器学习
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhangquan1995.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  zhangquan1995
email: zhangquan2014@foxmail.com
weibo_username: zhangquan1995
zhihu_username: zhangquan1995

description_footer:

#gitment
comment_gitment_repo: zhangquan1995.github.io
comment_gitment_clientId: 61c2858fcad8e31a384a
comment_gitment_clientSecret: a42b6e659f4321919ec21b8af2db7e41ffbaf9e2


# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: e5a35e62751b1f5305cfc174a374fd4d
google_analytics_id: UA-116772911-1 # google 分析追踪id

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
